/**
 * Seed script: Chennai date venues for Fuse Explore.
 * Run: node api/scripts/seedVenues.js
 */
import dotenv from "dotenv";
dotenv.config();
import mongoose from "mongoose";
import Venue from "../models/Venue.js";

const VENUES = [
  {
    name: "The Writers Café",
    description: "Cosy literary café with artisan coffee, book-lined walls, and quiet corners perfect for a first date.",
    city: "Chennai",
    area: "Nungambakkam",
    address: "56, Haddows Road, Nungambakkam, Chennai",
    category: "cafe",
    cuisine: "Continental, Coffee",
    priceRange: "mid",
    bookingFee: 49,
    venueCommissionPct: 0,
    dinerDiscountPct: 0,
    images: ["https://images.fusedating.co.in/venues/writers-cafe.jpg"],
    tags: ["books", "quiet", "first date", "coffee"],
    interestTags: ["reading", "coffee", "writing", "art"],
    openingHours: "8 AM – 10 PM",
    maxPartySize: 6,
    isFuseVerified: true,
    isActive: true,
    sortOrder: 1,
    rating: 4.5,
  },
  {
    name: "Amethyst Café",
    description: "Sprawling garden café in a heritage bungalow. Romantic, laid-back, and Fuse-verified for a safe first date.",
    city: "Chennai",
    area: "Gopalapuram",
    address: "No. 6, Whites Road, Royapettah, Chennai",
    category: "cafe",
    cuisine: "Multi-cuisine, Desserts",
    priceRange: "mid",
    bookingFee: 49,
    venueCommissionPct: 0,
    dinerDiscountPct: 0,
    images: ["https://images.fusedating.co.in/venues/amethyst.jpg"],
    tags: ["garden", "heritage", "brunch", "romantic"],
    interestTags: ["photography", "coffee", "food", "nature"],
    openingHours: "9 AM – 8 PM",
    maxPartySize: 8,
    isFuseVerified: true,
    isActive: true,
    sortOrder: 2,
    rating: 4.6,
  },
  {
    name: "Ciclo Café",
    description: "Chennai's beloved cycle-themed café with a warm vibe and excellent filter coffee.",
    city: "Chennai",
    area: "Besant Nagar",
    address: "9, Besant Avenue, Besant Nagar, Chennai",
    category: "cafe",
    cuisine: "South Indian, Coffee, Desserts",
    priceRange: "budget",
    bookingFee: 29,
    venueCommissionPct: 0,
    dinerDiscountPct: 0,
    images: ["https://images.fusedating.co.in/venues/ciclo-cafe.jpg"],
    tags: ["filter coffee", "casual", "beachside", "bikes"],
    interestTags: ["cycling", "coffee", "food"],
    openingHours: "8 AM – 11 PM",
    maxPartySize: 6,
    isFuseVerified: true,
    isActive: true,
    sortOrder: 3,
    rating: 4.4,
  },
  {
    name: "Prego — Westin",
    description: "Upscale Italian restaurant with harbour views and a warm romantic setting.",
    city: "Chennai",
    area: "Velachery",
    address: "154, Velachery Main Road, Chennai",
    category: "restaurant",
    cuisine: "Italian",
    priceRange: "premium",
    bookingFee: 99,
    venueCommissionPct: 0,
    dinerDiscountPct: 0,
    images: ["https://images.fusedating.co.in/venues/prego.jpg"],
    tags: ["Italian", "fine dining", "romantic", "anniversary"],
    interestTags: ["food", "travel", "wine"],
    openingHours: "12 PM – 3 PM, 7 PM – 11 PM",
    maxPartySize: 8,
    isFuseVerified: true,
    isActive: true,
    sortOrder: 4,
    rating: 4.7,
  },
  {
    name: "Savya Rasa",
    description: "Award-winning South Indian fine dining. Perfect for a culturally rich date.",
    city: "Chennai",
    area: "Khader Nawaz Khan Road",
    address: "12, KNK Road, Nungambakkam, Chennai",
    category: "restaurant",
    cuisine: "South Indian",
    priceRange: "premium",
    bookingFee: 79,
    venueCommissionPct: 0,
    dinerDiscountPct: 0,
    images: ["https://images.fusedating.co.in/venues/savya-rasa.jpg"],
    tags: ["South Indian", "fine dining", "heritage"],
    interestTags: ["food", "culture", "cooking"],
    openingHours: "12:30 PM – 3 PM, 7 PM – 10:30 PM",
    maxPartySize: 6,
    isFuseVerified: true,
    isActive: true,
    sortOrder: 5,
    rating: 4.7,
  },
  {
    name: "Bay 146 — Rooftop Bar & Grill",
    description: "Trendy rooftop with city skyline views, craft cocktails, and a lively weekend atmosphere.",
    city: "Chennai",
    area: "Nungambakkam",
    address: "146, Nungambakkam High Road, Chennai",
    category: "rooftop",
    cuisine: "Continental, Grills, Cocktails",
    priceRange: "premium",
    bookingFee: 99,
    venueCommissionPct: 0,
    dinerDiscountPct: 0,
    images: ["https://images.fusedating.co.in/venues/bay146.jpg"],
    tags: ["rooftop", "cocktails", "skyline", "weekend"],
    interestTags: ["food", "nightlife", "music"],
    openingHours: "6 PM – 1 AM",
    maxPartySize: 10,
    isFuseVerified: true,
    isActive: true,
    sortOrder: 6,
    rating: 4.3,
  },
  {
    name: "Mad Over Donuts",
    description: "Fun, colourful donut café. Great for a casual sweet date.",
    city: "Chennai",
    area: "Phoenix Marketcity",
    address: "Phoenix Marketcity, Velachery, Chennai",
    category: "dessert",
    cuisine: "Desserts, Coffee",
    priceRange: "budget",
    bookingFee: 29,
    venueCommissionPct: 0,
    dinerDiscountPct: 0,
    images: ["https://images.fusedating.co.in/venues/mod.jpg"],
    tags: ["donuts", "sweet", "fun", "casual"],
    interestTags: ["food", "baking", "desserts"],
    openingHours: "10 AM – 10 PM",
    maxPartySize: 4,
    isFuseVerified: true,
    isActive: true,
    sortOrder: 7,
    rating: 4.2,
  },
  {
    name: "Focaccia — ITC Grand Chola",
    description: "Elegant Italian at one of Chennai's finest hotels. Perfect for a special evening.",
    city: "Chennai",
    area: "Guindy",
    address: "ITC Grand Chola, 63, Mount Road, Chennai",
    category: "restaurant",
    cuisine: "Italian",
    priceRange: "premium",
    bookingFee: 99,
    venueCommissionPct: 0,
    dinerDiscountPct: 0,
    images: ["https://images.fusedating.co.in/venues/focaccia.jpg"],
    tags: ["Italian", "luxury", "special occasion"],
    interestTags: ["food", "travel", "wine"],
    openingHours: "12:30 PM – 3 PM, 7 PM – 11 PM",
    maxPartySize: 6,
    isFuseVerified: true,
    isActive: true,
    sortOrder: 8,
    rating: 4.8,
  },
];

async function seed() {
  await mongoose.connect(process.env.MONGO_URI);
  console.log("Connected to MongoDB.");

  for (const v of VENUES) {
    await Venue.updateOne({ name: v.name, city: v.city }, { $set: v }, { upsert: true });
    console.log(`✓ ${v.name}`);
  }

  console.log(`\n✅ Seeded ${VENUES.length} venues.`);
  await mongoose.disconnect();
}

seed().catch((err) => {
  console.error("Seed failed:", err);
  process.exit(1);
});
